### ISSUE TITLE
Add support for Bearer token

### ISSUE THREAD

**Issue by Deuchnord** [anaynayak/buildnotify#121]
I'm using Drone CI for my personal development, which uses a Bearer token associated to the user account to authenticate and access the CCMenu entrypoint:

```bash
curl --request GET \
  --url https://example.com/api/badges/Me/Project/cc.xml \
  --header 'authorization: Bearer aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789'
```

From a point of view of security, using a Bearer token is not a bad idea. Is it possible to add support for Bearer tokens instead of the classic user/password?

**Comment by anaynayak** [comment]
@Deuchnord thanks  for reporting this. Yes it should be possible to add this support. Feel free to raise a PR if you want to. I'm a bit busy in the near term but should be able to get it in a week or so.

**Comment by Deuchnord** [comment]
I'm not an expert of Python and Qt but I'll try to do this :)

**Comment by luchiago** [comment]
Hi, this issue still need help?

**Comment by Deuchnord** [comment]
I'm still working on it but didn't take the time to create a PR.
I made another one before to enhance the windows (#124), to make this issue easier to develop (especially placing the new UI elements). Would be nice if it could be reviewed :slightly_smiling_face:

**Comment by anaynayak** [comment]
Sorry. I'll be able to get to that PR tonight or early morning. Currently
don't have access to a laptop.

**Comment by Deuchnord** [comment]
> @Deuchnord for the ui elements, Are you thinking of this being an additional label/text combination ? I almost feel the need to hide this somewhere(collapsible/advanced settings) so that everyone else doesn't see few extra options.

I was actually thinking about a combo box in the credential part, with two options:
- Username/password (default choice)
- Authorization bearer token

If the token option is chosen, then the Username field disappears, and the Password field is renamed "Token" (it's only aesthetics, the logic remains the same).
Something like this:

![Username/password fields](https://user-images.githubusercontent.com/7600265/66423108-471af680-ea0b-11e9-856a-92c949db2b51.png)

![Bearer token field](https://user-images.githubusercontent.com/7600265/66423340-c7415c00-ea0b-11e9-8782-8c0c167c11a7.png)

**Comment by anaynayak** [comment]
Thanks for the screenshots. Very clear 👍 

We should definitely hide the token like for passwords since this I believe this can be used for other actions on behalf of the user. same for storage via keychain if available.
