### ISSUE TITLE
Update when showing the drop down menu

### ISSUE THREAD

**Issue by anaynayak** [anaynayak/buildnotify#14]
Originally reported by: **Robert Cotey (Bitbucket: [coteyr](https://bitbucket.org/coteyr), GitHub: [coteyr](https://github.com/coteyr))**

----------------------------------------

The drop down menu should update when you click/expand the menu. That is the data you want to see when you do that.

This is trivial to implement.

----------------------------------------
- Bitbucket: https://bitbucket.org/Anay/buildnotify/issue/14

**Comment by Bu11etmagnet** [comment]
This should be optional and not unconditional. A refresh may take a long time, and the user will be confused/annoyed if the menu appears several seconds after clicking on the icon.

**Comment by JonnyRa** [comment]
I don't know if this is related/the motivation for this but I see a couple of update bugs which could be related.

I can log them separately if you want but was just trying to see if there was already an open issue and this seems to be in the right ballpark:

Sometimes the colour shown in the notification area won't be correct and mousing over or clicking on it will swap it to the correct colour but then it swaps back again when you move the mouse away or click off the context menu.  It just seems to be to do with it being stale but it could also be that I'm only interested in a subset of the CI jobs that we have going and maybe one is showing the state of the subset and the other is showing the state of all.

The other one is that sometimes I get a double context menu from clicking on the buildnotify coloured blob - literally the same menu stacked on top of itself twice, including all projects and static buttons (Exit, Preferences, About).  This doesn't happen straight away but I think once it's there it, it persists until you close and restart.
