### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by anaynayak** [anaynayak/buildnotify#15]
Originally reported by: **Anay Nayak (Bitbucket: [Anay](https://bitbucket.org/Anay), GitHub: [Anay](https://github.com/anaynayak))**

----------------------------------------

With Ubuntu 14.04 the intent is to have only Python 3 on the desktop CD images. 

Incorporate changes and test application in Python 3.3 and 2.7. This should also provide an opportunity to refactor most of the code and write more tests.

----------------------------------------
- Bitbucket: https://bitbucket.org/Anay/buildnotify/issue/15

**Comment by jrabbit** [comment]
I have py3 working locally need to organize the commits a bit first tho

**Comment by anaynayak** [comment]
@jrabbit that would be quite useful. Are you using something for compatibility mode across 2 and 3 ? Or only 3 ? I had tried something similar with PR #36 but never to to testing it. Feel free to raise a separate PR.

**Comment by jrabbit** [comment]
Some of it is six compat some isn't, pyqt5 isn't being distributed for 2.7 nor really supported. There's nothing stopping us from just using six everywhere though. I think the two times i used 2to3 were on network code, this could also be eased by simply using `requests`. Also Keyring only is on py3 so it may make sense to just drop support

**Comment by anaynayak** [comment]
Yes. makes sense to drop support for 2.7 👍

**Comment by anaynayak** [comment]
Closing this one now that Python3 is in master.
