### ISSUE TITLE
Allow users to define watchers aliases

### ISSUE THREAD

**Issue by benftwc** [anaynayak/buildnotify#169]
Usage suggestion : I'm using multiples watchers, but repository names doesn't fit application names and it would be great to replace the repository name with an alias.

**Comment by anaynayak** [comment]
@benftwc wanted to understand this a bit more. Is the repository name too long and hence it is difficult to identify? Or is it that you need meaningful names to be attached against individual repositories ? Buildnotify currently lets you define a prefix against an endpoint. 

If you need an alternative label against each build, I suspect this will be harder to support without complicating the UI
