### ISSUE TITLE
Allow left-click on tray icon

### ISSUE THREAD

**Issue by probonopd** [anaynayak/buildnotify#193]
I am using the tray icon as part of my global menu bar.

![image](https://user-images.githubusercontent.com/2480569/101239482-1f472180-36e8-11eb-9066-c3d4c906f4fe.png)

It would be nice if it would allow left-click on tray icon to bring up the menu, instead of/in addition to the right-click.

**Comment by anaynayak** [comment]
Thanks for reporting this @probonopd . Will look into how this can work.

**Comment by anaynayak** [comment]
@probonopd will it be possible for you to check the behavior with https://github.com/anaynayak/buildnotify/pull/194 ? I have tried it out on a Mac but based on what I've read, the behavior differs across various operating systems.

**Comment by probonopd** [comment]
I can confirm that this works for me on [helloSystem](https://hellosystem.github.io/docs). :+1: 
Thank you very much.

**Comment by anaynayak** [comment]
I have merged the MR. Thanks for all the help.
