### ISSUE TITLE
Supported CI systems

### ISSUE THREAD

**Issue by johnjohndoe** [anaynayak/buildnotify#206]
Could you please add a list of continuous integrations systems which are supported?

I found out that [_Travis CI_](https://docs.travis-ci.com/user/cc-menu) works fine. I wonder if [_F-Droid_](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=30&from=&hidebots=0&hideanons=1&hideliu=1&limit=500) and _GitHub Actions_ provide a compatible machine-readable API?

**Comment by anaynayak** [comment]
Github actions still has an [open feature request ](https://github.community/t/feature-request-publish-workflow-status-in-cctray-format-xml/16815)
