### ISSUE TITLE
Cannot accept self-signed TLS certificate

### ISSUE THREAD

**Issue by anaynayak** [anaynayak/buildnotify#27]
Originally reported by: **Anonymous**

----------------------------------------

It would be nice buildnotify offered an option to accept invalid/self-signed certificates

----------------------------------------
- Bitbucket: https://bitbucket.org/Anay/buildnotify/issue/27

**Comment by Zialus** [comment]
I'm not getting the prompt to skip the SSL check :confused:

**Comment by anaynayak** [comment]
I suspect the switch over to `requests` library has reintroduced this bug since the original logic no longer works.

**Comment by Zialus** [comment]
@anaynayak any updates on this?

**Comment by anaynayak** [comment]
@Zialus I just checked and it should be working. Let me know if you see any issues.

Steps to reproduce with a dummy server (in a buildnotify checkout directory):
```
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem
npx http-server@0.12.3 -e json -S
```

Adding https://localhost:8080/data/cctray.xml gives a certificate warning and on clicking yes, the list of projects is displayed.

**Comment by Zialus** [comment]
@anaynayak , thanks for thr update

It seems to be working if I use the [git](https://aur.archlinux.org/packages/buildnotify-git/) version but not the [released](https://aur.archlinux.org/packages/buildnotify/) version

**Comment by anaynayak** [comment]
I have release v2.1.0 to pypi and the snapcraft should build automatically. I'm not fully sure how this flows downstream to archlinux.

**Comment by Zialus** [comment]
No worries, thanks for the update.
