### ISSUE TITLE
Support URLs without scheme

### ISSUE THREAD

**Issue by anaynayak** [anaynayak/buildnotify#31]
Originally reported by: **Anonymous**

----------------------------------------

Hudson 3.2.2 writes cc.xml like this:

```
#!xml

<Project webUrl="10.10.10.10:8080/job/delete_002/" name="delete_002" />
```
Clicking on any entry on the tray menu results only in an error popup:

```
Unable to detect uri-scheme of "10.10.10.10:8080/job/delete_002/"
```
It would be nice if buildnotify could recognize if the scheme was omitted, or it would punt and assume HTTP.

----------------------------------------
- Bitbucket: https://bitbucket.org/Anay/buildnotify/issue/31

**Comment by Bu11etmagnet** [comment]
Does not work with BuildNotify 1.0.0

**Comment by anaynayak** [comment]
Thanks for reporting this @Bu11etmagnet . Working on the fix right now.

**Comment by anaynayak** [comment]
@Bu11etmagnet this should be working now in latest master. Will push a new version shortly.

**Comment by Bu11etmagnet** [comment]
Is this going to be visible in `pip` ? Currently
```
$ sudo pip install buildnotify --upgrade
Requirement already up-to-date: buildnotify in /usr/local/lib/python2.7/dist-packages
```

**Comment by Bu11etmagnet** [comment]
Btw, I'm the Anonymous who reported this originally on Bitbucket :)

**Comment by anaynayak** [comment]
Apologies I haven't been able to push this to pip yet. Will try to do that in the next couple of days. 

> Btw, I'm the Anonymous who reported this originally on Bitbucket :)

Oh wow. Thanks for reporting it again 👍

**Comment by anaynayak** [comment]
This should be fixed in http://pypi.python.org/pypi/BuildNotify/1.0.3
