### ISSUE TITLE
Support URLs without scheme in jobs

### ISSUE THREAD

**Issue by Bu11etmagnet** [anaynayak/buildnotify#42]
Our CI server (Hudson 3.2.2) returns a cc.xml that looks like this:

`<Projects><Project webUrl="10.69.194.15:8080/job/delete_002/" name="delete_002" lastBuildLabel="6" lastBuildTime="2016-11-24T12:39:19Z" lastBuildStatus="Unknown" activity="Sleeping"/></Projects>
`

This may be the cause why clicking on any job in the drop-down menu results in an error popup:

`Unble to detect the URI-scheme of "10.69.194.15:8080/job/delete_002/"`

#31 was meant to represent this, but I wasn't clear enough. It's not about the missing scheme in the server URL. It's about the missing scheme in the URLs of individual jobs.

As far as I can see, buildnotify does the right thing in project.py, calling `urlparse(props['url'], 'http')`. Still, clicking on any job on the drop-down menu fails with the "Unable to detect URI-scheme" error.

I tried to debug buildnotifyapplet.py but pudb crashed :(

**Comment by anaynayak** [comment]
This is now fixed in v1.0.4. Apologies for the incomplete fix in #31 . 

`pip install --pre --index-url https://test.pypi.org/simple buildnotify`

Let me know if that works. Will roll out 1.0.4 to pip shortly.

**Comment by anaynayak** [comment]
1.0.4 has been pushed to pypi as well

**Comment by Bu11etmagnet** [comment]
Verified working with 1.0.4, many thanks.
