### ISSUE TITLE
do not auto-subscribe to new branches unless all were already selected

### ISSUE THREAD

**Issue by MartinNowak** [anaynayak/buildnotify#53]
At least semaphore CI only has a single cc.xml endpoint that lists build statuses for all branches (https://github.com/renderedtext/semaphore-docs-new/blob/a9a2f51eca9f624a8a8d00ba320b7a87c467d544/source/docs/cctry.md).
If you're only interested in master and stable, but not in pull requests, then it's possible to only select those.
![grafik](https://user-images.githubusercontent.com/288976/39418719-4e5dab0c-4c5c-11e8-9ab7-83fd9c00af70.png)
Unfortunately at the time new pull requests are opened, they are listed by the endpoint and buildnotify automatically selects/subscribes to those.

I'd suggest that the *All* state should be saved separately (if not already done) and be used to decide whether or not to auto-subscribe to new branches.

**Comment by Deuchnord** [comment]
@anaynayak is it ok if I take this? :slightly_smiling_face:

**Comment by anaynayak** [comment]
Yes please. Thanks @Deuchnord
