### ISSUE TITLE
Nothing happens after install/run

### ISSUE THREAD

**Issue by JonnyRa** [anaynayak/buildnotify#54]
Hi,

I've just installed the program in ubuntu 18 using apt-get.  I seem to have version `0.3.5-1` (from apt show buildnotify)

I get the following messages.  It then stays running but nothing happens:

```
Gtk-Message: 09:26:11.273: Failed to load module "canberra-gtk-module"
No systemtrayicon available
```

I was expecting something to appear in the gnome system tray.

Could you help?

Cheers

Jonny

**Comment by JonnyRa** [comment]
So I've managed to remove the first message by running:

```sudo apt-get install libcanberra-gtk-module```

I'm still seeing the issue though so presumably it's down to lack of tray icon.

**Comment by jrabbit** [comment]
Looks like the version in ubuntu is rather old and uses QT4

**Comment by JonnyRa** [comment]
That seems to be working, although there's no icon :
![screenshot from 2018-06-08 09-37-08](https://user-images.githubusercontent.com/6482442/41147929-8ded2740-6aff-11e8-98c4-046481c16006.png)

for future reference - you install by doing this:
```
chmod u+x setup.py
sh setup.sh
sudo setup.py install
```

**Comment by JonnyRa** [comment]
Thanks for the reply btw! :)

**Comment by anaynayak** [comment]
Apologies for the delayed response. This one slipped off my radar. A newer version should be available via pip but dependencies are still a pain with pyqt. Things should get better with building a snap via #46 .

I'm assuming that things are now working fine for @JonnyRa  based on things suggested by @jrabbit  (thanks!)  . so closing this one for now.

**Comment by anaynayak** [comment]
👍 Makes sense.  A PR will be quite helpful.
